##
# This file is part of the pl.wrzasq.commons.
#
# @license http://mit-license.org/ The MIT license
# @copyright 2014 - 2019 © by Rafal Wrzeszcz - Wrzasq.pl.
##

#FIXME: https://github.com/travis-ci/travis-ci/issues/753

language: "java"

sudo: false

dist: "trusty"

branches:
    except:
        - "/^release-/"

jdk:
    - "openjdk8"
    - "oraclejdk8"
    - "oraclejdk9"
    - "openjdk11"
    - "oraclejdk11"

# TODO: temporary as delombok won't work here
matrix:
    include:
        -
            jdk: "openjdk10"
            before_install:
                - "rm ${JAVA_HOME}/lib/security/cacerts"
                - "ln -s /etc/ssl/certs/java/cacerts ${JAVA_HOME}/lib/security/cacerts"
    allow_failures:
        -
            jdk: "openjdk11"
        -
            jdk: "oraclejdk11"

env:
    global:
        - "AWS_REGION=eu-central-1"
        -
            secure: |-
                lUCACNi4KWY2g29RBdH7bBu+gQqg2eh0tgBaiBYV/kIfWPIcnZRQ4KdEmoakKeogFudko6D/1SvIfnC8kCezMTdsFVVmH9+/1kIKTzd
                PJgFRtBKC4knqobhx7Y5nrOXLsoaKnW1GEpA2iUmZGE0ciEKEE1eQEod+U2f4rAlRGOvj3FQJ7HYRF16dTk4xKR/iLgqhF2+azU7w8v
                yRATPn+ez2HywBrZUwkLMdDeyaY0UMP22YQTYd6MucKAKQKhpsQvTph66dMuR1wcaAJzDRwIBikLn21Y6caEydpzp831x82EVrk+kPR
                JVvKLRPElpgE+QIfmaD2oLcOGtpYZ1opMNaIqVfvFp/kSIoWm8OHPRlpLQaFwyD040PaYXrf7FCjHxOF3eKYXkkZaq/W4FqOKAkCO6/
                B14a2LT6kJ3VdzX5wJyyvJ5zZk7QoltAjawxyaoWlNER0O6igUfDszUvCz560QK64FJzNCHe/MFNJbITuILDKMrpEUdRUu98OKN0UWQ
                +L+ivYFaJ7WULYr81plT3zafgp0pfRUD27u0KsfZNugvEmFyyB+iA/JFBDbFrqNqHCQKpszNkpQTDOQ5oIAttZ860SHyEBnuDwY5Q7R
                IW4kPqRq/JVU+VAeipWo6wko8KaWXIo+Auy7iqJIlX/BCNF1GbjFFjHnkd4f+ZSAc=
        -
            secure: |-
                HYu31wyOrrolQAGsADNxhMrU1hsDbL39cMHq5yD6rCnqbhC1IAKaBYmTLuQVN7XEPybKW6Y2HUCQJ/GKr89lKHsnywaE5LE+7bGeWO1
                AUuZs+7chQgAhRCJRVXNLO37+ClufGhXVIDC5bH8JJ6PdvAhL0XQxWHFzP00XoJl0YXRcLO3lPHEe2OAUWtyPLxu1fZIDPawb4rQucJ
                jQAeiMf6xRLP3HwgL3yeyDjLTrcXATrFKNA7GMXOsBSZhzWYkim46eu2L9/74KzGXcEeDwje+AZ0Fxtxg2LeaOYBv2GUYxCGISIHr6w
                A8Tud2sxMaU1j3mADAUFSK3VbfVggTemWXTc3+JbVx6cS0mryAD7brhlc2wQKzaNefuJwuP8uI4UVuGS5xrhxvK/NBXFczsveeZxMmB
                lk9iau00g8m+F+4kDtGzlT9im1vpoUIRHnn6scaZE0BgpoqvJ65F2RQtd3xbdxC0Hoh7arx+wVsqsy0QdDgv/kt/ymrHDJZA5tmD8pU
                I5Ull4ZcHgMRk69nVSlQEImdLqI7L9m5oLRGnbcgJ7lSS/JPjFwcVzuVndovAdU6BLkMCD5pEU5fc2fUEztW0G/pe3cuWrLtYrTW3vO
                ke/ZVoZqC7zTC+gmM9SOXC7uCtNxdKC4xdmXp+9L3lb+5HtluFOTl9ZxtKoM9UqwQ=
        -
            secure: |-
                qMNieVkgp/C0YDxQM81LJwRk9gH5XYavCmvOfepC4LZ6ne4DK/RuQxgv0IUw6SYHkw5Sy5Z6re+lqaSBm7gIhRweG+dVEEUQlQfFqKE
                alN+2Dvg6uB1cVT9sjFLFgQy+2avcEI8UJlQmslJkPeNQF1vB8PEohhBXksbeJVcVY7eMMbPog4TjY1WsbtT3VEPpDFkuPePkwRr0Iq
                zBToQHv92BP+WI2wX6yQpxG8wbGGpKdZD9bbsDRxlLw7hHreoOZ88lRg2pALla6MGj2UCklddqLQSYTKkceruUUveMyYMsnkVxY1cNJ
                2iO8wKP1A6tXg+4BCaVG7R+pQNl/PH7UQIwocwS+v6zfCXs/QCMIfPpHoIrwvmXs05E491+Vx1aX56t8a5fNg8UXoLUi4zttYldzi38
                lxno0DEkD+4JYWgGRUq+/CCg2pT2AOCjBgqUYF47iAvT7MPU1+/gI5CDpMdja22+eJ/G5MY0ofrhy4uO+qu+3LX5+qWIVRbyWPJQC+o
                VT5htB2/daIu3/0jfa6JJYGdXDJ6oPukCagH7P737XluG+fppboyeZuutASTTFB3fbzqytFTYe4i6NxPSav4OhHX6uukjx4gkCTnVJa
                Es2upCe6aH+wNVn/2bTkawtVDsVFUHZ3bLpOSJivRW7q1ITewMroLDR6ar7fU6BaM=
        -
            secure: |-
                BpMD4tHmxw2yyz9DSSL0L1QEMMqpj9mCSpFw6e1rdn+cFEn4InnjciXACPPLLwibqld/ja+8IuDpRCwT/nQsagRIa3hRt8O0CajrSRF
                hxY5PTR2eeCvhca2kS9Fg7ECvlQw3NxK3KxYTWpDl5lM3VS9/Ps6hKzTg+tO8uyUF0m48L2rfiY/Z68IpfcNu/SsINzXZZU4cgMiixk
                HV4xiN9b1MtRujh602GBfmeGj5sCJLiZPrPdtN4NpuvIYsGD2lfyD5uqE8gsvw47XOgHt2YBsf+VBZTgi4uf+0kGG6xiPbE5momwXDC
                x/C66eLlxnbMziUdoUr6VbBH607yR7s+Kc9iDsqWADbXSzpEcH8jlGsLadGKyVHt/mvgpF0fdIFwzpxG3zRXoO+UJhNL6Mf8piFvwy3
                1epBqlGj2Undji5eKJax7ua91hTG+0FsiD+UfTpJ7lZX+ZwUcE8AYHO6nHK3i7hPtWrF6ARpwE4DSHgvoIISCp8x03EVlwnQBxK1A+A
                hNWoLFcCp3QvwwZRPWwj9LqkXJhaCdNAkare83gE0BoFdAA8T67EUkp2OXu0IZvgBXzpw9Zo/h/fJUIEajYzVhq4zJPxgZJatkN/8WQ
                oMEHOHut8BK9b+4/f5eDBl4qc7xkraN0va58o6HtLLFnjMrDFD7i1hNlY7tiEA42I=
        -
            secure: |-
                ucrioy5LBk/lArX59An9Fg5fAFF84y9pWGTL8p3wUUoSJgxFlsSfGcoEXtYBI9G9ZGSm6h9JR0k+WsyNfedCLTC0nHPQ9OcVJuor3U8
                Hm/20RIQ4/ZCyIMsn5rkdg1d40z5POxnfWXT0LlPVXgs5BP+qunLlsTwoPcegLslWq755cDBCe/JaW2goNX5qSCOoQgnXzOOboD3LiJ
                BtkHw06MAAlj+zjnsaiIGkLj4/Zf31i38/Se96bGdOnkxjtrCPH0Y/49EuCuRhUaOUbKDAGjY2oeAIfOfLb6YLf6ki2vXfq5kI4wNbh
                iFsgb6rD7S3cdWx+4lqNEodz+FkvwUBcecVLTi5s1RZ6P9ubjbHT7gLEjlMVWvq8VmXwXcvGZwmb7y8QMuIvFDZJ5Z/TgoGX859zaRw
                GqsC6hgsfRl2e/5kWWbYB3GuxqzddexqQQYHk5JVmWNxIGmZvpAN693PyuTKoZ+6rgbI47Pqolo/PdOTBll7bxq1hjX1voRw4K9wJpw
                muwiG8HkotmyK4yyzwyzbBH6Cn1CkQlAxr36kKoq19xPtTmQkgAQEGJiC5ebIdmW8QWAVxgxwtiuTZxEIR46zyBXy1bkZ6OpSR/5bWa
                x23FMSvJGW07GCxbpvCL1UHx8Bd7HWEhxhX4dKXDUwjXTii5sMtqCyUGH2ne1sQPo=

# this is not a boolean, this is a Linux `true` command to simply override this step
install: "true"

script: "mvn -e verify site"

after_script: "mvn -e coveralls:report"

    - "eval \"$(ssh-agent -s)\""
    - "git config user.name \"Travis CI\""
    - "git config user.email \"office@wrzasq.pl\""
    - "openssl aes-256-cbc -md sha256 -k \"${SECRET}\" -in .travis/gpg_key.enc -out .travis/gpg_key -d"
    - "openssl aes-256-cbc -md sha256 -k \"${SECRET}\" -in .travis/id_rsa.enc -out .travis/id_rsa -d"
    # this is needed to avoid duplicated key error as we have two deploys on `master`
    - "rm -f ~/.gnupg/*.gpg"
    - "gpg --fast-import .travis/gpg_key"
    - "chmod 600 .travis/id_rsa"
    - "ssh-add .travis/id_rsa"
    - "echo -e \"Host github.com\\n    StrictHostKeyChecking no\\n\" >> ~/.ssh/config"
    # this actually does the job, but we need it to produce artifacts for "releases" provider
    # entire "before_deploy" will not be executed if there is no deploy to be processed
    - "./.travis/release.sh"
    - "export TRAVIS_TAG=$(git describe --abbrev=0)"

deploy:
    -
        provider: "releases"
        skip_cleanup: true
        api_key: "${GITHUB_TOKEN}"
        file_glob: true
        file: "*/target/*.jar"
        on:
            branch: "master"
            condition: "${TRAVIS_EVENT_TYPE} == push"
            jdk: "oraclejdk8"

cache:
    directories:
        - "${HOME}/.m2/"

before_cache: "rm -rf ${HOME}/.m2/repository/pl/wrzasq/commons"

notifications:
    webhooks:
        urls:
            - "https://webhooks.gitter.im/e/fcdaff0aebb4484e5e41"
