##
# This file is part of the ChillDev-Commons.
#
# @license http://mit-license.org/ The MIT license
# @copyright 2014 - 2015 © by Rafal Wrzeszcz - Wrzasq.pl.
##

#FIXME: https://github.com/travis-ci/travis-ci/issues/753

language: "java"

sudo: false

jdk:
    - "oraclejdk8"

script: "mvn verify"

after_script: "mvn site coveralls:report"

notifications:
    webhooks:
        urls:
            - "https://webhooks.gitter.im/e/54252a58453d00b848db"
