##
# This file is part of the ChillDev-Commons.
#
# @license http://mit-license.org/ The MIT license
# @author Rafal Wrzeszcz <rafal.wrzeszcz@wrzasq.pl>
# @copyright 2014 © by Rafal Wrzeszcz - Wrzasq.pl.
# @version 0.0.1
# @since 0.0.1
# @category ChillDev-Commons
##

#FIXME: https://github.com/travis-ci/travis-ci/issues/753

language: "java"

jdk:
    - "openjdk7"
    - "oraclejdk7"
    - "oraclejdk8"

before_install: "sudo apt-get install texlive-latex-base texlive-latex-recommended"

script: "mvn test verify"

after_script: "mvn site coveralls:cobertura"
